trigger: none

pool: 
  vmImage: ubuntu-latest

stages:

- stage: Deploy
  displayName: 'Deploy Stage'
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          az login
      displayName: 'Login Azure'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          ids=$(az webapp list --query '[0].id' -o tsv)
          repo_url=https://github.com/shivmodi1203/my-book-store.git
          az webapp deployment source config --branch master --manual-integration --repo-url $repo_url --ids $ids
          az webapp deployment source sync --ids $ids
      displayName: 'Push Azure'