# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: trivy@1
  inputs:
    version: 'latest'
    image: 'nginx:alpine3.18'
    severities: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
    exitCode: '0'
  displayName: "Trivy"

- script: |
    high_count=$(grep HIGH /tmp/*.json | wc -l)
    critical_count=$(grep CRITICAL /tmp/*.json | wc -l)
    echo $high_count
    echo $critical_count
    if [ $high_count -ge 3 ] || [ $critical_count -ge 3 ]; then
      echo "Terminating pipeline due to 3 or more severities found. ${high_count}"
      exit 1
    else
      echo "No action required. Severities found: $severity_count"
    fi
  displayName: 'Check Trivy Severities'